name: LittleMinecraftVanillaExtension
main: ml.codenoodles.lmve.Main
api-version: 1.15
author: netbenix
version: Beta-1.2.0
commands:
    lmve:
      usage: /<command>
      description: LMVE Main Command